//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaPresentacion.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public decimal ITBIS {
            get {
                return ((decimal)(this["ITBIS"]));
            }
            set {
                this["ITBIS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int CFinalSecuencia {
            get {
                return ((int)(this["CFinalSecuencia"]));
            }
            set {
                this["CFinalSecuencia"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime FechaVencimiento {
            get {
                return ((global::System.DateTime)(this["FechaVencimiento"]));
            }
            set {
                this["FechaVencimiento"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int CFiscalSecuencia {
            get {
                return ((int)(this["CFiscalSecuencia"]));
            }
            set {
                this["CFiscalSecuencia"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-A2S2DPV\\SQLEXPRESS;Initial Catalog=SistemaFacturacionRepuesto" +
            "Joan;Integrated Security=True;MultipleActiveResultSets=True;Application Name=Ent" +
            "ityFramework")]
        public string SistemaFacturacionRepuestoJoanConnectionString {
            get {
                return ((string)(this["SistemaFacturacionRepuestoJoanConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int CNotaDeCredito {
            get {
                return ((int)(this["CNotaDeCredito"]));
            }
            set {
                this["CNotaDeCredito"] = value;
            }
        }
    }
}
