
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CapaDatos
{

using System;
    using System.Collections.Generic;
    
public partial class Cliente
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Cliente()
    {

        this.Facturas = new HashSet<Factura>();

    }


    public int ClienteID { get; set; }

    public string Nombre { get; set; }

    public string CedulaORnc { get; set; }

    public string Direccion { get; set; }

    public string Contacto_1 { get; set; }

    public string Contacto_2 { get; set; }

    public Nullable<double> Descuento { get; set; }

    public Nullable<double> Credito { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Factura> Facturas { get; set; }

}

}
