
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CapaDatos
{

using System;
    using System.Collections.Generic;
    
public partial class DetalleNotaDeCredito
{

    public int DetalleNotaDeCreditoID { get; set; }

    public int NotaDeCreditoID { get; set; }

    public int ProductoID { get; set; }

    public double CantDevuelta { get; set; }

    public double CantInventariada { get; set; }

    public decimal Precio { get; set; }

    public string Comentario { get; set; }



    public virtual NotasDeCredito NotasDeCredito { get; set; }

    public virtual Producto Producto { get; set; }

}

}
