
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CapaDatos
{

using System;
    using System.Collections.Generic;
    
public partial class Factura
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Factura()
    {

        this.DetalleFacturas = new HashSet<DetalleFactura>();

        this.LineasCreditoVentas = new HashSet<LineasCreditoVenta>();

        this.NotasDeCreditoes = new HashSet<NotasDeCredito>();

    }


    public int FacturaID { get; set; }

    public int ClienteID { get; set; }

    public System.DateTime Fecha { get; set; }

    public int TipoPagoID { get; set; }

    public Nullable<System.DateTime> FechaVencimiento { get; set; }

    public int UserID { get; set; }

    public string NCF { get; set; }

    public string RNC { get; set; }

    public int TipoFacturaID { get; set; }

    public string Entidad { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DetalleFactura> DetalleFacturas { get; set; }

    public virtual TiposPago TiposPago { get; set; }

    public virtual User User { get; set; }

    public virtual Cliente Cliente { get; set; }

    public virtual TiposFactura TiposFactura { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<LineasCreditoVenta> LineasCreditoVentas { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<NotasDeCredito> NotasDeCreditoes { get; set; }

}

}
