
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CapaDatos
{

using System;
    using System.Collections.Generic;
    
public partial class OrdenesCompra
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public OrdenesCompra()
    {

        this.DetalleOrdenesCompras = new HashSet<DetalleOrdenesCompra>();

        this.FacturasCompras = new HashSet<FacturasCompra>();

    }


    public int OrdencompraID { get; set; }

    public int ProveedorID { get; set; }

    public System.DateTime FechaPedido { get; set; }

    public Nullable<System.DateTime> FechaCompletado { get; set; }

    public bool Estatus { get; set; }



    public virtual DetalleOrdenesCompra DetalleOrdenesCompra { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DetalleOrdenesCompra> DetalleOrdenesCompras { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<FacturasCompra> FacturasCompras { get; set; }

}

}
